language: python
matrix:
    include:
        - python: '3.8'
        - python: 3.8
          arch: arm64
sudo: false
# running in the container-based infrastructure without access to sudo
before_install:
      - cd bindings/pydeck/requirements
install:
      - pip install -r requirements-dev.txt
      - curl https://raw.github.com/creationix/nvm/master/install.sh | sh
      - nvm install 10.16.0
      - nvm use 10.16.0
      - pip install -e . --install-option "--build_all"
      - pip install -e . --install-option "--build_all" --verbose
script:
    - cd bindings/pydeck
    - pytest --cov=pydeck
